version: '3.7'
services:
#  consul:
#    build: docker/discovery-com.example.accountapi.service/.
#    container_name: consul
#    image: consul
#    restart: always
#    hostname: consul
#    ports:
#      - "8500:8500" #HTTP SERVER


#  redis:
#    build: docker/redis-server/.
#    image: local-redis
#    ports:
#      - "6379:6379"
#    volumes:
#      - `/data:/data:rw

  postgresql:
    build: docker/database-server/.
    image: personal-db
    container_name: personal-db
    ports:
      - "5432:5432"
    volumes:
      - ${DOCKER_BASE}/database-server/data:/var/lib/postgresql/data:rw
      - ${DOCKER_BASE}/database-server/backup:/var/lib/postgresql/backup:rw

  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    ports:
    - "5672:5672"
    - "15672:15672"
