version: '3.7'
services:
#  consul:
#    build: docker/discovery-com.example.accountapi.service/.
#    container_name: consul
#    image: consul
#    restart: always
#    hostname: consul
#    ports:
#      - "8500:8500" #HTTP SERVER
  postgresql:
    build: docker/database-server/.
    image: personal-db
    container_name: personal-db
    ports:
      - "5432:5432"
    volumes:
      - ${DOCKER_BASE}/database-server/data:/var/lib/postgresql/data:rw
      - ${DOCKER_BASE}/database-server/backup:/var/lib/postgresql/backup:rw

#  web:
#    build:
#      context: ./
#      dockerfile: ./docker/web/Dockerfile
#    image: web
#    container_name: web
#    ports:
#      - "8080:8080" #WildFly App
#    environment:
#      - "SPRING_PROFILES_ACTIVE=docker"
#    depends_on:
#      - gateway-api

#  gateway-api:
#    build:
#      context: ./
#      dockerfile: ./docker/gateway-api/Dockerfile
#    image: gateway-api
#    container_name: gateway-api
#    ports:
#      - "8085:8080"
#    environment:
#      - "SPRING_PROFILES_ACTIVE=docker"
#    depends_on:
#      - tradelog-api

  tradelog-api:
    build:
      context: ./
      dockerfile: ./docker/tradelog-api/Dockerfile
    image: tradelog-api
    container_name: tradelog-api
    ports:
      - "8083:8080"
    environment:
      - "SPRING_PROFILES_ACTIVE=docker"
    depends_on:
      - postgresql

  stockdata-api:
    build:
      context: ./
      dockerfile: ./docker/stockdata-api/Dockerfile
    image: stockdata-api
    container_name: stockdata-api
    ports:
      - "8086:8080"
    environment:
      - "SPRING_PROFILES_ACTIVE=docker"
    depends_on:
      - postgresql

#  accountapi:
#    build: account/.
#    image: accountapi
#    container_name: accountapi
#    ports:
#      - "8082:8080" #App
#    depends_on:
#      - postgresql



#  redis:
#    build: docker/redis-server/.
#    image: local-redis
#    ports:
#      - "6379:6379"
#    volumes:
#      - `/data:/data:rw

