runtime: java
env: flex

#service: library

#handlers:
#  - url: /.*
#    script: ignored

automatic_scaling:
  min_num_instances: 1
  max_num_instances: 1

#resources:
#  cpu: 1
#  memory_gb: 1
#  disk_size_gb: 1
#  volumes:
#    - name: ramdisk1
#      volume_type: tmpfs
#      size_gb: 0.5