runtime: java
env: flex
instance_class: F1

service: library

#beta_settings:
#  cloud_sql_instances: pt20200316:us-central1:db-pt-001

#handlers:
#  - url: /.*
#    script: ignored

env_variables:
  SPRING_PROFILES_ACTIVE: "prod"

#resources:
#  cpu: 1
#  memory_gb: 1
#  disk_size_gb: 1
#  volumes:
#    - name: ramdisk1
#      volume_type: tmpfs
#      size_gb: 0.5